"""add_missing_fk_indexes

Revision ID: 752aa0cfbb2a
Revises: 9b7c1d4e2a63
Create Date: 2026-07-25 16:49:44.264189
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '752aa0cfbb2a'
down_revision = '9b7c1d4e2a63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activated_rules_result_id'), 'activated_rules', ['result_id'], unique=False)
    op.create_index(op.f('ix_activated_rules_rule_id'), 'activated_rules', ['rule_id'], unique=False)
    op.create_index(op.f('ix_clinical_history_patient_id'), 'clinical_history', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_probabilities_disease_id'), 'clinical_probabilities', ['disease_id'], unique=False)
    op.create_index(op.f('ix_clinical_probabilities_symptom_id'), 'clinical_probabilities', ['symptom_id'], unique=False)
    op.create_index(op.f('ix_clinical_probabilities_variable_id'), 'clinical_probabilities', ['variable_id'], unique=False)
    op.create_index(op.f('ix_diseases_species_id'), 'diseases', ['species_id'], unique=False)
    op.create_index(op.f('ix_evaluation_facts_evaluation_id'), 'evaluation_facts', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_evaluations_patient_id'), 'evaluations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_evaluations_veterinarian_id'), 'evaluations', ['veterinarian_id'], unique=False)
    op.create_index(op.f('ix_fact_definitions_clinical_variable_id'), 'fact_definitions', ['clinical_variable_id'], unique=False)
    op.create_index(op.f('ix_fact_definitions_fact_key'), 'fact_definitions', ['fact_key'], unique=False)
    op.create_index(op.f('ix_fact_definitions_id'), 'fact_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_fact_definitions_species_id'), 'fact_definitions', ['species_id'], unique=False)
    op.create_index(op.f('ix_fact_definitions_symptom_id'), 'fact_definitions', ['symptom_id'], unique=False)
    op.create_index(op.f('ix_inference_results_disease_id'), 'inference_results', ['disease_id'], unique=False)
    op.create_index(op.f('ix_inference_results_evaluation_id'), 'inference_results', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_inference_results_risk_level_id'), 'inference_results', ['risk_level_id'], unique=False)
    op.create_index(op.f('ix_inference_rules_disease_id'), 'inference_rules', ['disease_id'], unique=False)
    op.create_index(op.f('ix_inference_rules_risk_level_id'), 'inference_rules', ['risk_level_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_id'), 'knowledge_sources', ['id'], unique=False)
    op.alter_column('owners', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_patients_breed_id'), 'patients', ['breed_id'], unique=False)
    op.create_index(op.f('ix_patients_created_by'), 'patients', ['created_by'], unique=False)
    op.create_index(op.f('ix_patients_owner_id'), 'patients', ['owner_id'], unique=False)
    op.create_index(op.f('ix_patients_species_id'), 'patients', ['species_id'], unique=False)
    op.create_index(op.f('ix_rule_conditions_rule_id'), 'rule_conditions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rule_references_id'), 'rule_references', ['id'], unique=False)
    op.create_index(op.f('ix_rule_references_rule_id'), 'rule_references', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rule_references_source_id'), 'rule_references', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_references_source_id'), table_name='rule_references')
    op.drop_index(op.f('ix_rule_references_rule_id'), table_name='rule_references')
    op.drop_index(op.f('ix_rule_references_id'), table_name='rule_references')
    op.drop_index(op.f('ix_rule_conditions_rule_id'), table_name='rule_conditions')
    op.drop_index(op.f('ix_patients_species_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_owner_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_by'), table_name='patients')
    op.drop_index(op.f('ix_patients_breed_id'), table_name='patients')
    op.alter_column('owners', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_knowledge_sources_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_inference_rules_risk_level_id'), table_name='inference_rules')
    op.drop_index(op.f('ix_inference_rules_disease_id'), table_name='inference_rules')
    op.drop_index(op.f('ix_inference_results_risk_level_id'), table_name='inference_results')
    op.drop_index(op.f('ix_inference_results_evaluation_id'), table_name='inference_results')
    op.drop_index(op.f('ix_inference_results_disease_id'), table_name='inference_results')
    op.drop_index(op.f('ix_fact_definitions_symptom_id'), table_name='fact_definitions')
    op.drop_index(op.f('ix_fact_definitions_species_id'), table_name='fact_definitions')
    op.drop_index(op.f('ix_fact_definitions_id'), table_name='fact_definitions')
    op.drop_index(op.f('ix_fact_definitions_fact_key'), table_name='fact_definitions')
    op.drop_index(op.f('ix_fact_definitions_clinical_variable_id'), table_name='fact_definitions')
    op.drop_index(op.f('ix_evaluations_veterinarian_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_patient_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluation_facts_evaluation_id'), table_name='evaluation_facts')
    op.drop_index(op.f('ix_diseases_species_id'), table_name='diseases')
    op.drop_index(op.f('ix_clinical_probabilities_variable_id'), table_name='clinical_probabilities')
    op.drop_index(op.f('ix_clinical_probabilities_symptom_id'), table_name='clinical_probabilities')
    op.drop_index(op.f('ix_clinical_probabilities_disease_id'), table_name='clinical_probabilities')
    op.drop_index(op.f('ix_clinical_history_patient_id'), table_name='clinical_history')
    op.drop_index(op.f('ix_activated_rules_rule_id'), table_name='activated_rules')
    op.drop_index(op.f('ix_activated_rules_result_id'), table_name='activated_rules')
    # ### end Alembic commands ###
