"""add_timestamp_and_soft_delete_mixins

Revision ID: 7c1f146683e0
Revises: 6c5dc6eed9ec
Create Date: 2026-07-25 17:20:58.298585
"""
from alembic import op
import sqlalchemy as sa


revision = '7c1f146683e0'
down_revision = '6c5dc6eed9ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activated_rules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('activated_rules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('breeds', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('breeds', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('breeds', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('clinical_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_clinical_history_evaluation_id'), 'clinical_history', ['evaluation_id'], unique=False)
    op.add_column('clinical_probabilities', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('clinical_probabilities', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('clinical_variables', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('clinical_variables', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('diseases', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('diseases', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('evaluation_facts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('evaluation_facts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('evaluations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fact_definitions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fact_definitions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('inference_results', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('inference_rules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('inference_rules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('knowledge_sources', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('knowledge_sources', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('owners', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('risk_levels', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('risk_levels', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('rule_conditions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('rule_conditions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('rule_references', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('rule_references', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('species', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('species', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('species', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('symptoms', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('symptoms', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('symptoms', 'updated_at')
    op.drop_column('symptoms', 'created_at')
    op.drop_column('species', 'is_active')
    op.drop_column('species', 'updated_at')
    op.drop_column('species', 'created_at')
    op.drop_column('rule_references', 'updated_at')
    op.drop_column('rule_references', 'created_at')
    op.drop_column('rule_conditions', 'updated_at')
    op.drop_column('rule_conditions', 'created_at')
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('risk_levels', 'updated_at')
    op.drop_column('risk_levels', 'created_at')
    op.drop_column('patients', 'updated_at')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_column('password_reset_tokens', 'updated_at')
    op.drop_column('owners', 'updated_at')
    op.drop_column('knowledge_sources', 'updated_at')
    op.drop_column('knowledge_sources', 'created_at')
    op.drop_column('inference_rules', 'updated_at')
    op.drop_column('inference_rules', 'created_at')
    op.drop_column('inference_results', 'updated_at')
    op.drop_column('fact_definitions', 'updated_at')
    op.drop_column('fact_definitions', 'created_at')
    op.drop_column('evaluations', 'updated_at')
    op.drop_column('evaluation_facts', 'updated_at')
    op.drop_column('evaluation_facts', 'created_at')
    op.drop_column('diseases', 'updated_at')
    op.drop_column('diseases', 'created_at')
    op.drop_column('clinical_variables', 'updated_at')
    op.drop_column('clinical_variables', 'created_at')
    op.drop_column('clinical_probabilities', 'updated_at')
    op.drop_column('clinical_probabilities', 'created_at')
    op.drop_index(op.f('ix_clinical_history_evaluation_id'), table_name='clinical_history')
    op.drop_column('clinical_history', 'updated_at')
    op.drop_column('breeds', 'is_active')
    op.drop_column('breeds', 'updated_at')
    op.drop_column('breeds', 'created_at')
    op.drop_column('activated_rules', 'updated_at')
    op.drop_column('activated_rules', 'created_at')
    # ### end Alembic commands ###
