"""add_timestamp_and_soft_delete_mixins

Revision ID: 7c1f146683e0
Revises: 6c5dc6eed9ec
Create Date: 2026-07-25 17:20:58.298585
"""
from alembic import op
import sqlalchemy as sa


revision = '7c1f146683e0'
down_revision = '6c5dc6eed9ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Guarded: see note in 752aa0cfbb2a about this database's non-linear history.
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def _add_column(table, column):
        existing = {c["name"] for c in inspector.get_columns(table)}
        if column.name not in existing:
            op.add_column(table, column)

    def _create_index(name, table, columns):
        existing = {ix["name"] for ix in inspector.get_indexes(table)}
        if name not in existing:
            op.create_index(op.f(name), table, columns, unique=False)

    def _ts_column():
        return lambda name: sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False)

    ts = _ts_column()

    _add_column('activated_rules', ts('created_at'))
    _add_column('activated_rules', ts('updated_at'))
    _add_column('breeds', ts('created_at'))
    _add_column('breeds', ts('updated_at'))
    _add_column('breeds', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    _add_column('clinical_history', ts('updated_at'))
    _create_index('ix_clinical_history_evaluation_id', 'clinical_history', ['evaluation_id'])
    _add_column('clinical_probabilities', ts('created_at'))
    _add_column('clinical_probabilities', ts('updated_at'))
    _add_column('clinical_variables', ts('created_at'))
    _add_column('clinical_variables', ts('updated_at'))
    _add_column('diseases', ts('created_at'))
    _add_column('diseases', ts('updated_at'))
    _add_column('evaluation_facts', ts('created_at'))
    _add_column('evaluation_facts', ts('updated_at'))
    _add_column('evaluations', ts('updated_at'))
    _add_column('fact_definitions', ts('created_at'))
    _add_column('fact_definitions', ts('updated_at'))
    _add_column('inference_results', ts('updated_at'))
    _add_column('inference_rules', ts('created_at'))
    _add_column('inference_rules', ts('updated_at'))
    _add_column('knowledge_sources', ts('created_at'))
    _add_column('knowledge_sources', ts('updated_at'))
    _add_column('owners', ts('updated_at'))
    _add_column('password_reset_tokens', ts('updated_at'))
    _create_index('ix_password_reset_tokens_id', 'password_reset_tokens', ['id'])
    _add_column('patients', ts('updated_at'))
    _add_column('risk_levels', ts('created_at'))
    _add_column('risk_levels', ts('updated_at'))
    _add_column('roles', ts('created_at'))
    _add_column('roles', ts('updated_at'))
    _add_column('roles', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    _add_column('rule_conditions', ts('created_at'))
    _add_column('rule_conditions', ts('updated_at'))
    _add_column('rule_references', ts('created_at'))
    _add_column('rule_references', ts('updated_at'))
    _add_column('species', ts('created_at'))
    _add_column('species', ts('updated_at'))
    _add_column('species', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    _add_column('symptoms', ts('created_at'))
    _add_column('symptoms', ts('updated_at'))
    _add_column('users', ts('created_at'))
    _add_column('users', ts('updated_at'))
    _create_index('ix_users_role_id', 'users', ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('symptoms', 'updated_at')
    op.drop_column('symptoms', 'created_at')
    op.drop_column('species', 'is_active')
    op.drop_column('species', 'updated_at')
    op.drop_column('species', 'created_at')
    op.drop_column('rule_references', 'updated_at')
    op.drop_column('rule_references', 'created_at')
    op.drop_column('rule_conditions', 'updated_at')
    op.drop_column('rule_conditions', 'created_at')
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('risk_levels', 'updated_at')
    op.drop_column('risk_levels', 'created_at')
    op.drop_column('patients', 'updated_at')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_column('password_reset_tokens', 'updated_at')
    op.drop_column('owners', 'updated_at')
    op.drop_column('knowledge_sources', 'updated_at')
    op.drop_column('knowledge_sources', 'created_at')
    op.drop_column('inference_rules', 'updated_at')
    op.drop_column('inference_rules', 'created_at')
    op.drop_column('inference_results', 'updated_at')
    op.drop_column('fact_definitions', 'updated_at')
    op.drop_column('fact_definitions', 'created_at')
    op.drop_column('evaluations', 'updated_at')
    op.drop_column('evaluation_facts', 'updated_at')
    op.drop_column('evaluation_facts', 'created_at')
    op.drop_column('diseases', 'updated_at')
    op.drop_column('diseases', 'created_at')
    op.drop_column('clinical_variables', 'updated_at')
    op.drop_column('clinical_variables', 'created_at')
    op.drop_column('clinical_probabilities', 'updated_at')
    op.drop_column('clinical_probabilities', 'created_at')
    op.drop_index(op.f('ix_clinical_history_evaluation_id'), table_name='clinical_history')
    op.drop_column('clinical_history', 'updated_at')
    op.drop_column('breeds', 'is_active')
    op.drop_column('breeds', 'updated_at')
    op.drop_column('breeds', 'created_at')
    op.drop_column('activated_rules', 'updated_at')
    op.drop_column('activated_rules', 'created_at')
    # ### end Alembic commands ###
