"""descripcion

Revision ID: 81bc1fcf6c62
Revises: 78c872599de8
Create Date: 2026-09-23 03:40:00.917817
"""
from alembic import op
import sqlalchemy as sa


revision = '81bc1fcf6c62'
down_revision = '78c872599de8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('breeds_species_id_fkey', 'breeds', type_='foreignkey')
    op.create_foreign_key(None, 'breeds', 'species', ['species_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'breeds', type_='foreignkey')
    op.create_foreign_key('breeds_species_id_fkey', 'breeds', 'species', ['species_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
