"""add bayesian inference support

Revision ID: b2aeb44f214b
Revises: 
Create Date: 2026-05-20 04:03:58.348371
"""
from alembic import op
import sqlalchemy as sa


revision = 'b2aeb44f214b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('species_id', 'name', name='uix_species_breed_name')
    )
    op.create_index(op.f('ix_breeds_id'), 'breeds', ['id'], unique=False)
    op.create_table('clinical_probabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=True),
    sa.Column('variable_id', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.String(length=100), nullable=True),
    sa.Column('probability_given_disease', sa.Float(), nullable=False),
    sa.Column('general_probability', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variable_id'], ['clinical_variables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_probabilities_id'), 'clinical_probabilities', ['id'], unique=False)
    op.add_column('diseases', sa.Column('base_probability', sa.Float(), nullable=True))
    op.add_column('inference_results', sa.Column('probability', sa.Float(), nullable=True))
    op.add_column('inference_results', sa.Column('inference_method', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('patients', sa.Column('breed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'owners', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'patients', 'breeds', ['breed_id'], ['id'])
    op.drop_column('patients', 'breed')
    op.drop_column('patients', 'tutor_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('tutor_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('breed', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'breed_id')
    op.drop_column('patients', 'owner_id')
    op.drop_column('inference_results', 'inference_method')
    op.drop_column('inference_results', 'probability')
    op.drop_column('diseases', 'base_probability')
    op.drop_index(op.f('ix_clinical_probabilities_id'), table_name='clinical_probabilities')
    op.drop_table('clinical_probabilities')
    op.drop_index(op.f('ix_breeds_id'), table_name='breeds')
    op.drop_table('breeds')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
