ROLE_ADMIN = "admin"
ROLE_VETERINARIAN = "veterinario"
ROLE_EVALUATOR = "evaluador"

READ_ROLES = (ROLE_ADMIN, ROLE_VETERINARIAN, ROLE_EVALUATOR)
WRITE_ROLES = (ROLE_ADMIN, ROLE_VETERINARIAN)
ADMIN_ROLES = (ROLE_ADMIN,)

RISK_LOW = "bajo"
RISK_MODERATE = "moderado"
RISK_HIGH = "alto"

DEFAULT_RISK_LEVEL = RISK_MODERATE
